### ISSUE TITLE
Marginal price calculation

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/carbon-sdk#68]
Each order should include a Marginal price value which indicates the current price in the order range.
### Expected return value
Order details should include the MarginalPrice value

### Flow
1. Order range between 1000-2000
2. Budget 1000 tokens
3. y-int (z) = 1000 //we currently set this value to match the budget on creation
4. Trader took 200 tokens out of the budget

SDK should be able to return the current starting price (Marginal Price) of the order as it is no longer the minPrice point.

### Example
This is a high level calculation (DO NO USE IT AS IS) to explain what we are trying to achieve
1. Identify how much of the budget was taken: 1-{available budget}/{y-int} = 1-(800/1000) = 20%
2. Identify how far down the range we are: {lowPrice}+{highPrice - lowPrice}*{1} = 1000+(2000-1000)*20%=1000+200=1200
result should indicate that the new Marginal Price is 1200

**Comment by barakman** [comment]
At least on the lower-layer of the SDK, this is already supported; see [here](https://github.com/bancorprotocol/carbon-sdk/blob/main/src/utils/encoders.ts#L60-L73).

**Comment by ashachaf** [comment]
as indicated, marginalRate is currently exposed as part of the decoded order details. 
closing this task as it is no longer needed.
